# Generated by Django 5.2.8 on 2025-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, to='salon.service'),
        ),
    ]
