# Generated by Django 5.2.8 on 2025-11-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_services'),
        ('salon', '0002_salon_address_salon_description_salon_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.salon'),
        ),
    ]
