# Generated by Django 5.2.8 on 2025-11-26 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('working_start', models.TimeField()),
                ('working_end', models.TimeField()),
                ('employees', models.ManyToManyField(blank=True, to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.salon')),
            ],
        ),
    ]
