# Generated by Django 5.2.8 on 2025-11-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
